# Generated by gallery/generate.py; do not edit.
function ars_creo_gallery:clear
# wheel-north: Starbuncle Wheel facing north
setblock 176 100 176 ars_creo:starbuncle_wheel[facing=north]
# wheel-south: Starbuncle Wheel facing south
setblock 180 100 176 ars_creo:starbuncle_wheel[facing=south]
# wheel-west: Starbuncle Wheel facing west
setblock 184 100 176 ars_creo:starbuncle_wheel[facing=west]
# wheel-east: Starbuncle Wheel facing east
setblock 188 100 176 ars_creo:starbuncle_wheel[facing=east]
# wheel-up: Starbuncle Wheel facing up
setblock 176 100 180 ars_creo:starbuncle_wheel[facing=up]
# wheel-down: Starbuncle Wheel facing down
setblock 180 100 180 ars_creo:starbuncle_wheel[facing=down]
# stock-control: stone stock rendering control
setblock 184 100 180 minecraft:stone
function ars_creo_gallery:verify
