# Generated by gallery/generate.py; do not edit.
execute unless block 176 100 176 ars_creo:starbuncle_wheel[facing=north] run tellraw @a {"text":"gallery mismatch: wheel-north","color":"red"}
execute unless block 180 100 176 ars_creo:starbuncle_wheel[facing=south] run tellraw @a {"text":"gallery mismatch: wheel-south","color":"red"}
execute unless block 184 100 176 ars_creo:starbuncle_wheel[facing=west] run tellraw @a {"text":"gallery mismatch: wheel-west","color":"red"}
execute unless block 188 100 176 ars_creo:starbuncle_wheel[facing=east] run tellraw @a {"text":"gallery mismatch: wheel-east","color":"red"}
execute unless block 176 100 180 ars_creo:starbuncle_wheel[facing=up] run tellraw @a {"text":"gallery mismatch: wheel-up","color":"red"}
execute unless block 180 100 180 ars_creo:starbuncle_wheel[facing=down] run tellraw @a {"text":"gallery mismatch: wheel-down","color":"red"}
execute unless block 184 100 180 minecraft:stone run tellraw @a {"text":"gallery mismatch: stock-control","color":"red"}
tellraw @a {"text":"Ars Creo gallery checked","color":"green"}
